### ISSUE TITLE
SASS 变量覆盖

### ISSUE THREAD

**Issue by luqin** [luqin/blog#17]
``` scss
/*1*/
$a: 1px !default;
$a: 2px !default;
$a: 3px;
$a: 4px !default;
$a: 5px;

.a {
  width: $a;
}

/*2*/
$b: 1px !default;
$b: 2px !default;
$b: 3px !default;

.b {
  width: $b;
}

/*3*/
$c: 1px;
$c: 2px !default;
$c: 4px;
$c: 3px !default;

.c {
  width: $c;
}

```

output:

``` css

/*1*/
.a {
  width: 5px;
}

/*2*/
.b {
  width: 1px;
}

/*3*/
.c {
  width: 4px;
}
```
